export const reducerCases = {
    SET_USER_INFO: "SET_USER_INFO",
    SET_NEW_USER: "SET_NEW_USER",
    SET_ALL_CONTACTS_PAGE: "SET_ALL_CONTACTS_PAGE",
    CHANGE_CURRENT_CHAT_USER: "CHANGE_CURRENT_CHAT_USER",
    SET_SOCKET: "SET_SOCKET",
    SET_MESSAGES: "SET_MESSAGES",
    ADD_MESSAGE: "ADD_MESSAGE",
    SET_USER_CONTACTS: "USER_CONTACTS",
    SET_EXIT_CHAT: "SET_EXIT_CHAT",
    SET_MESSAGES_READ: "SET_MESSAGES_READ",
    SET_ONLINE_USERS: "SET_ONLINE_USERS",
    SET_MESSAGES_SEARCH: "SET_MESSAGES_SEARCH",
    SET_CONTACT_SEARCH: "SET_CONTACT_SEARCH",
  };
  